In [10]:
import pandas as pd
import numpy as np
import random


¿Qué diferencia hay entre una Serie y un DataFrame?
Momento de trabajar con Series. Contestad a las siguientes preguntas:
Crea dos listas:
   

Una serie  es unidimensional y un DataFrame es bidiomensional.

Una que se llame "valores" que tenga 7 números aleatorios.

In [ ]:
valores =pd.random.random_sample()

In [5]:
valores= [2,5,7,9,5,8,3]
valores

[2, 5, 7, 9, 5, 8, 3]

Otra que se llame "indices" que tenga 7 strings que se llamen como los días de la semana.

In [15]:
indices = ['Lunes','Martes','Miercoles','Jueves','Viernes','Sabado', 'Domingo']
indices

['Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sabado', 'Domingo']

A partir de estas dos listas cread una Serie donde la variable "valores" sean los valores de la Serie y la variable indices sean los índices de la Serie.

In [17]:
serie1 = pd.Series(valores, index = indices)
serie1

Lunes        2
Martes       5
Miercoles    7
Jueves       9
Viernes      5
Sabado       8
Domingo      3
dtype: int64

A partir de las dos listas anteriores cread un diccionario usando un bucle for. Para hacer esto tenemos el método zip que nos permite iterar por dos listas a la vez. Más informción sobre este método aquí.

In [57]:
zip1= zip(indices,valores)



In [58]:
diccionario1={}

for k,v in zip1:

    diccionario1.update({k:v})
  


In [62]:
diccionario1

{'Lunes': 2,
 'Martes': 5,
 'Miercoles': 7,
 'Jueves': 9,
 'Viernes': 5,
 'Sabado': 8,
 'Domingo': 3}

In [60]:
diccionario2 ={}
for k,v in zip(indices,valores):

    diccionario2.update({k:v})

In [61]:
diccionario2

{'Lunes': 2,
 'Martes': 5,
 'Miercoles': 7,
 'Jueves': 9,
 'Viernes': 5,
 'Sabado': 8,
 'Domingo': 3}

Probamos dos formas de crear el diccionario a traves de un zip ya que tenemos que recordar que los zip SON DE UN SOLO USO! 
La mejor opcion seria la que incluye la creacion del zip en el for.

Crea una Serie con el diccionario creado en el punto anterior.

In [63]:
serie2 = pd.Series(diccionario2)
serie2

Lunes        2
Martes       5
Miercoles    7
Jueves       9
Viernes      5
Sabado       8
Domingo      3
dtype: int64

In [ ]:
#¿Qué forma tiene esta última Serie?

In [64]:
serie2.shape

(7,)

In [ ]:
#¿Qué tipo de datos tiene?

In [65]:
serie2.values

array([2, 5, 7, 9, 5, 8, 3])

In [ ]:
#¿Cuáles son los índices de la Serie?¿Y los values?

In [66]:
serie2.index

Index(['Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sabado',
       'Domingo'],
      dtype='object')

In [ ]:
#Extraed el valor para el índice "lunes"

In [67]:
serie2['Lunes']

2

In [ ]:
#Extraed el valor para el índice "lunes", "martes" y "miércoles".¿Qué tipo de datos tiene?

In [71]:
serie2[['Lunes','Martes', 'Miercoles']]

Lunes        2
Martes       5
Miercoles    7
dtype: int64

Tiene datos tipo Interger.

In [ ]:
#Extraed el valor para el índice "lunes" y "domingo".

In [72]:
serie2[['Lunes','Domingo']]

Lunes      2
Domingo    3
dtype: int64

Es el turno de los DataFrames
Cread un array de dos dimensiones con 4 filas y 3 columnas

In [42]:
array = np.random.randint(1,10,(4,3))
array

array([[3, 9, 5],
       [1, 2, 3],
       [5, 1, 6],
       [8, 3, 1]])

In [ ]:
#Convertid el array en un DataFrame donde las columnas se llamen "España", "Francia" e "Italia".

In [43]:
nombres = ['España', 'Francia', 'Italia']

In [45]:
dataf = pd.DataFrame(array, columns= nombres)
dataf

España  Francia  Italia
0       3        9       5
1       1        2       3
2       5        1       6
3       8        3       1

In [ ]:
#Descargad el archivo "medallas" y cargad el DataFrame con la siguiente línea de código:
#df = pd.read_csv("medallas.csv", index_col=["País"])

In [53]:
df = pd.read_csv("_medallas.csv", index_col=["País"])
df

Unnamed: 0   Oro  Plata  Bronce
País                                            
China                     1  1473    994     720
Japón                     2  1032   1037     985
Corea del Sur             3   745    663     827
Irán                      4   179    181     197
Kazajistán                5   155    158     224
India                     6   154    202     315
Tailandia                 7   132    175     278
Indonesia                 8   112    131     240
China Taipéi              9    99    144     276
Corea del Norte          10    91    120     235

In [ ]:
#Usando el loc extraed todas las columnas de la fila.

In [76]:
df.loc['China',:]

Unnamed: 0       1
Oro           1473
Plata          994
Bronce         720
Name: China, dtype: int64

In [ ]:
#Usando el loc extraed todas las columnas de China e Irán.

In [78]:
df.loc[['China','Irán'], :]

Unnamed: 0   Oro  Plata  Bronce
País                                  
China           1  1473    994     720
Irán            4   179    181     197

In [ ]:
#Usando el loc extraed solo las columnas de "Oro", "Plata" y "Bronce" de China e Irán.

In [81]:
df.loc[ ['China','Irán'],['Oro','Plata', 'Bronce']]

Oro  Plata  Bronce
País                      
China  1473    994     720
Irán    179    181     197

In [ ]:
#Usando el iloc extraed la información de la India. Devolved todas las columnas.

In [86]:
df.iloc[ : list(df.India)]

AttributeError: 'DataFrame' object has no attribute 'India'

In [ ]:
#Usando el iloc extraed todas las columnas de los paises que estén en posición impar. La primera que nos tendría que salir es Japón
#  y la última Corea del Norte.

In [89]:
df.iloc[1 : :2 ,  : ]

Unnamed: 0   Oro  Plata  Bronce
País                                            
Japón                     2  1032   1037     985
Irán                      4   179    181     197
India                     6   154    202     315
Indonesia                 8   112    131     240
Corea del Norte          10    91    120     235

In [ ]:
#Utilizando el código del ejercicio anterior, seleccionad unicamente las columnas "Oro", "Plata" y "Bronce".

In [130]:
df.iloc[1 : :2 , df.Oro, df.Bronce]

TypeError: list expected at most 1 argument, got 2

Contestad a las siguientes preguntas:

In [ ]:
#¿Qué país consiguió más de 200 medallas de oro?


In [98]:
df.loc[df.Oro >200, :]

Unnamed: 0   Oro  Plata  Bronce
País                                          
China                   1  1473    994     720
Japón                   2  1032   1037     985
Corea del Sur           3   745    663     827

In [ ]:
#¿Qué país consiguió más de 200 medallas de oro y más de 1000 de plata?

In [101]:
df.loc[(df.Oro >200) & (df.Plata >1000), :]

Unnamed: 0   Oro  Plata  Bronce
País                                  
Japón           2  1032   1037     985

In [ ]:
#¿Qué país consiguió más de 200 medallas de oro o más de 700 de bronce?

In [103]:
df.loc[(df.Oro >200) | (df.Bronce >700), :]

Unnamed: 0   Oro  Plata  Bronce
País                                          
China                   1  1473    994     720
Japón                   2  1032   1037     985
Corea del Sur           3   745    663     827

In [ ]:
#Como vemos hay una columna que se llama Unnamed: 0 que no nos interesa. Eliminad esa columna.

In [129]:
df.drop(0)

KeyError: '[0] not found in axis'

In [124]:
df.values

array([[   1, 1473,  994,  720],
       [   2, 1032, 1037,  985],
       [   3,  745,  663,  827],
       [   4,  179,  181,  197],
       [   5,  155,  158,  224],
       [   6,  154,  202,  315],
       [   7,  132,  175,  278],
       [   8,  112,  131,  240],
       [   9,   99,  144,  276],
       [  10,   91,  120,  235]])

In [ ]:
#Cread una nueva columma que se llame "total" que sea el resultado de la suma de todas las medallas obtenidas por cada país.

In [125]:
df.insert(4,'Total',(df.Oro + df.Plata +df.Bronce))

In [126]:
df

Unnamed: 0   Oro  Plata  Bronce  Total
País                                                   
China                     1  1473    994     720   3187
Japón                     2  1032   1037     985   3054
Corea del Sur             3   745    663     827   2235
Irán                      4   179    181     197    557
Kazajistán                5   155    158     224    537
India                     6   154    202     315    671
Tailandia                 7   132    175     278    585
Indonesia                 8   112    131     240    483
China Taipéi              9    99    144     276    519
Corea del Norte          10    91    120     235    446