##                             NumPy II Indexacion

In [1]:
import numpy as np

1-Cread un array de dos dimensiones de 5 filas y 3 columnas. 

In [19]:
matriz = np.random.rand(5,3)
matriz

array([[0.88855315, 0.6171639 , 0.65996577],
       [0.6634174 , 0.99832563, 0.80759309],
       [0.29289975, 0.7907105 , 0.59749001],
       [0.31992092, 0.00441935, 0.08730543],
       [0.24340437, 0.56456342, 0.76856503]])

Sobre el array creado anteriormente, extraed:
- El valor de la primera fila y la segunda columna.


In [20]:
matriz[0,1]

0.6171638975994557

- Los valores de la segunda fila y las dos primeras columnas.


In [21]:
matriz[1,0:2]

array([0.6634174 , 0.99832563])

- Extraed las filas pares (incluyendo la 0) y todas las columnas.


In [23]:
matriz[1::2,:] #reveerlo!

array([[0.6634174 , 0.99832563, 0.80759309],
       [0.31992092, 0.00441935, 0.08730543]])

- Extraed los valores que sean mayores que 0.5.


In [24]:
matriz [matriz >0.5]

array([0.88855315, 0.6171639 , 0.65996577, 0.6634174 , 0.99832563,
       0.80759309, 0.7907105 , 0.59749001, 0.56456342, 0.76856503])

- Extraed los valores menores que 0.2 o mayores que 0.5

In [25]:
matriz [(matriz < 0.2) | (matriz > 0.5)]

array([0.88855315, 0.6171639 , 0.65996577, 0.6634174 , 0.99832563,
       0.80759309, 0.7907105 , 0.59749001, 0.00441935, 0.08730543,
       0.56456342, 0.76856503])

2- Cread dos array de tres dimensiones:

El primero de 2 matrices, 5 filas y 3 columnas.




In [27]:
array1 = np.random.rand(2,5,3)
array1

array([[[0.48233594, 0.78682439, 0.71064661],
        [0.21039272, 0.85781627, 0.14273615],
        [0.29427296, 0.16278695, 0.66803981],
        [0.45102792, 0.3210061 , 0.97845575],
        [0.65068711, 0.14188833, 0.03518194]],

       [[0.9462709 , 0.69473481, 0.98756436],
        [0.79403704, 0.52903522, 0.75090665],
        [0.02747404, 0.06384143, 0.38576564],
        [0.45377559, 0.43974941, 0.92948384],
        [0.102307  , 0.36913464, 0.40442778]]])

El segundo de 3 matrices, 2 filas y 5 columnas.

In [30]:
array2 = np.ones((3,2,5))
array2

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

- Haced un análisis exploratorio de los array creados. Recordad que en el ejercicio de ayer nos creamos una función para esto.


In [67]:
def propiedades_array(array):
    tipo=f'Los elementos son de tipo {array.dtype}'
    tamaño=f'Tiene {array.size} elementos'
    forma=f'Su forma es: {array.shape}'
    dimension=f'Es de {array.ndim} dimensiones'
    return tipo,tamaño,forma,dimension

In [68]:
propiedades_array(array1)

('Los elementos son de tipo float64',
 'Tiene 30 elementos',
 'Su forma es: (2, 5, 3)',
 'Es de 3 dimensiones')

In [34]:
propiedades_array(array2)

(dtype('float64'), 30, (3, 2, 5), 3)

- Sumad los dos arrays. ¿Podéis? ¿Por qué?


In [36]:
np.add(array1,array2)

ValueError: operands could not be broadcast together with shapes (2,5,3) (3,2,5) 

`No podemos sumarlos porque tienen distinta forma.`

- Para cambiar la forma de un array y poder hacer operaciones entre arrays que tienen distintas formas hemos aprendido dos métodos:
.reshape()
.transpose()
Utiliza estas dos funciones para cambiar la forma de los array y hacer operaciones entre ellos.

Vamos a modificar solamente el array 1 con ambos metodos, convirtiendolo en la forma del array2.

In [40]:
array11 =array1.transpose(2,0,1) #Necesito definir una nueva variable para que queden los cambios, porque el metodo transpose() NO sobreescribe.

`Al metodo  transpose() lo aplicamos directamente sobre nuestro array y  vamos a especificar el indice donde se encuentra ubicado el valor que necesitamos en esa posicion.`

In [42]:
np.add(array11,array2) #Realizamos la suma de ambos array.

array([[[1.48233594, 1.21039272, 1.29427296, 1.45102792, 1.65068711],
        [1.9462709 , 1.79403704, 1.02747404, 1.45377559, 1.102307  ]],

       [[1.78682439, 1.85781627, 1.16278695, 1.3210061 , 1.14188833],
        [1.69473481, 1.52903522, 1.06384143, 1.43974941, 1.36913464]],

       [[1.71064661, 1.14273615, 1.66803981, 1.97845575, 1.03518194],
        [1.98756436, 1.75090665, 1.38576564, 1.92948384, 1.40442778]]])

In [45]:
array111 = np.reshape(array1, (3,2,5))
array111

array([[[0.48233594, 0.78682439, 0.71064661, 0.21039272, 0.85781627],
        [0.14273615, 0.29427296, 0.16278695, 0.66803981, 0.45102792]],

       [[0.3210061 , 0.97845575, 0.65068711, 0.14188833, 0.03518194],
        [0.9462709 , 0.69473481, 0.98756436, 0.79403704, 0.52903522]],

       [[0.75090665, 0.02747404, 0.06384143, 0.38576564, 0.45377559],
        [0.43974941, 0.92948384, 0.102307  , 0.36913464, 0.40442778]]])

`Para el metodo reshape  tenemos que llamar a np y luego especifica sobre que array trabajamos y lo que especificamos es directamente la forma que queremos tenga nuestro array.`

In [46]:
np.subtract(array2, array111)# Realizamos la resta de ambos array.

array([[[0.51766406, 0.21317561, 0.28935339, 0.78960728, 0.14218373],
        [0.85726385, 0.70572704, 0.83721305, 0.33196019, 0.54897208]],

       [[0.6789939 , 0.02154425, 0.34931289, 0.85811167, 0.96481806],
        [0.0537291 , 0.30526519, 0.01243564, 0.20596296, 0.47096478]],

       [[0.24909335, 0.97252596, 0.93615857, 0.61423436, 0.54622441],
        [0.56025059, 0.07051616, 0.897693  , 0.63086536, 0.59557222]]])