## NumPy I


### 1- Cread tres arrays: de una, dos y tres dimensiones.
(Lo podéis hacer usando los métodos de random que hemos aprendido o a través de listas em algunos casos.)

In [1]:
import numpy as np

- El array de 2 dimensiones debe ser de 2 filas y 3 columnas

In [2]:
array_1=np.random.randint(0,10,(2,3))
array_1

array([[7, 4, 7],
       [0, 3, 7]])

- El array de 3 dimensiones debe ser de 2 matrices, 3 filas y 5 columnas

In [3]:
array_2=np.random.randint(0,10,(2,3,5))
array_2

array([[[9, 7, 3, 0, 5],
        [7, 0, 6, 4, 4],
        [9, 3, 3, 8, 0]],

       [[1, 0, 6, 6, 8],
        [9, 5, 4, 3, 5],
        [2, 8, 3, 5, 7]]])

Chequed las las propiedades básicas de cada array que os hayáis creado. Usad en una función que nos devuelva las propiedades de una array que le pasemos.

In [4]:
def propiedades_array(array):
    tipo=f'Los elementos son de tipo {array.dtype}'
    tamaño=f'Tiene {array.size} elementos'
    forma=f'Su forma es: {array.shape}'
    dimension=f'Es de {array.ndim} dimensiones'
    return tipo,tamaño,forma,dimension

In [5]:
propiedades_array(array_1)

('Los elementos son de tipo int64',
 'Tiene 6 elementos',
 'Su forma es: (2, 3)',
 'Es de 2 dimensiones')

In [6]:
propiedades_array(array_2)

('Los elementos son de tipo int64',
 'Tiene 30 elementos',
 'Su forma es: (2, 3, 5)',
 'Es de 3 dimensiones')

Cread una matriz identidad de dos dimensiones de 3 filas y 3 columnas

In [7]:
matriz=np.identity(3)
matriz

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Cread una matriz de tres dimensiones de unos igual a la martiz de tres dimensiones creada en el primer ejercicio.

In [8]:
matrz_2=np.ones_like(array_2)
matrz_2

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

Es el momento de hacer algunas operaciones entre arrays

- ¿Se puede sumar el array de dos dimensiones que creamos en el primer ejecicios a la matriz identidad? ¿Por qué?


In [9]:
array_1.add(matriz)

AttributeError: 'numpy.ndarray' object has no attribute 'add'

`No se pueden sumar porque tienen diferente número de elementos.`


En caso de que no se puedan sumar, busca una solución para sumar una matriz identidad a otra. La solución puede ser crear un array nuevo.


In [ ]:
matriz_3=np.empty_like(matriz)
matriz_3

array([[4.65059360e-310, 0.00000000e+000, 2.35541533e-312],
       [2.31297541e-312, 1.29441743e-312, 2.41907520e-312],
       [2.05833592e-312, 9.76118064e-313, 3.95252517e-322]])

In [ ]:
np.add(matriz,matriz_3)

array([[1.00000000e+000, 0.00000000e+000, 2.35541533e-312],
       [2.31297541e-312, 1.00000000e+000, 2.41907520e-312],
       [2.05833592e-312, 9.76118064e-313, 1.00000000e+000]])

Multiplicad la matriz identidad por la nueva matriz que os creasteis en el ejercicio anterior.


In [ ]:
np.multiply(matriz,matriz_3)

array([[4.65059360e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 1.29441743e-312, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 3.95252517e-322]])

Dividid las dos matricess


In [ ]:
np.divide(matriz,matriz_3)

/tmp/ipykernel_1582/3345737900.py:2: RuntimeWarning: overflow encountered in true_divide
  np.divide(matriz,matriz_3)
/tmp/ipykernel_1582/3345737900.py:2: RuntimeWarning: invalid value encountered in true_divide
  np.divide(matriz,matriz_3)


array([[inf, nan,  0.],
       [ 0., inf,  0.],
       [ 0.,  0., inf]])

In [ ]:
np.divide(matriz_3,matriz)

/tmp/ipykernel_1582/4129110066.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.divide(matriz_3,matriz)
/tmp/ipykernel_1582/4129110066.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.divide(matriz_3,matriz)


array([[4.65059360e-310,             nan,             inf],
       [            inf, 1.29441743e-312,             inf],
       [            inf,             inf, 3.95252517e-322]])

`Nos da Nan en la posición [0][1] porque está dividiendo 0/0 y devuelve valor indeterminado.`