## NUNMPY IV Conjuntos

In [2]:
import numpy as np

¿Cómo podemos crear dos arrays de dos dimensiones usando el método random_sample que tengan los mismos valores?

In [3]:
#usando el método semilla (.seed())
np.random.seed(1)
array_1=np.random.random_sample((3,5))
array_2=np.random.random_sample((3,5))
array_1


array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
        1.46755891e-01],
       [9.23385948e-02, 1.86260211e-01, 3.45560727e-01, 3.96767474e-01,
        5.38816734e-01],
       [4.19194514e-01, 6.85219500e-01, 2.04452250e-01, 8.78117436e-01,
        2.73875932e-02]])

In [4]:
array_2

array([[0.67046751, 0.4173048 , 0.55868983, 0.14038694, 0.19810149],
       [0.80074457, 0.96826158, 0.31342418, 0.69232262, 0.87638915],
       [0.89460666, 0.08504421, 0.03905478, 0.16983042, 0.8781425 ]])

Cread los siguientes arrays:

Un array de tres dimensiones con distribución uniforme de 2 x 3 x 5, con números entre 0 y 10, que no tengan decimales y extrae sus valores únicos almacenándolos en una variable.

In [5]:
dist_1=np.round(np.random.uniform(0,10,size=(2,3,5)),decimals=0)
dist_1

array([[[ 1.,  4., 10.,  5.,  7.],
        [ 3.,  7.,  8.,  0.,  8.],
        [10.,  7.,  3.,  8.,  1.]],

       [[ 4.,  9.,  3.,  3.,  1.],
        [ 0.,  7.,  2.,  3.,  5.],
        [ 1.,  6.,  1.,  6.,  7.]]])

In [6]:
unicos_1=np.unique(dist_1)
unicos_1

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

Un array de tres dimensiones con distribución binomial de 2 x 3 x 5, con probabilidad de 0.3 y número de pruebas igual a 10. Igual que antes, extrae sus valores únicos y guarda los datos en una variable.

In [7]:
dist_2=np.random.binomial(10,0.3,size=(2,3,5))
dist_2

array([[[1, 3, 4, 3, 1],
        [3, 4, 3, 5, 3],
        [5, 1, 1, 4, 3]],

       [[2, 5, 2, 4, 4],
        [5, 3, 4, 2, 2],
        [5, 3, 6, 4, 3]]])

In [8]:
unicos_2=np.unique(dist_2)
unicos_2

array([1, 2, 3, 4, 5, 6])

En esta lección hemos aprendido algunos métodos de teórias de conjuntos. Usando los arrays de elementos únicos obtenidos en el ejercicio anterior realizad las siguientes operaciones:  
⚠️ Explicar cada uno de los outputs que os salgan. Que significa cada una de estas operaciones que hemos ido extrayendo?

Elementos comunes entre los dos arrays

In [9]:
np.intersect1d(unicos_1,unicos_2)
#obtenemos los elementos ordenados que son comunes en los dos arrays, en este caso unicos tambien de cada array

array([1., 2., 3., 4., 5., 6.])

Unión de los dos arrays

In [10]:
np.union1d(unicos_1,unicos_2)
#obtenemos un array ordenado de todos los elementos no repetidos de ambos arrays de unicos

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

¿Qué elementos están en el array derivado de la distribución uniforme y no en los únicos de la distribución binomial? Extrae los valores númericos

In [11]:
np.setdiff1d(unicos_1,unicos_2)
#obtenemos los valores unicos del array_1(uniforme) que no estan en el array_2(binomial)

array([ 0.,  7.,  8.,  9., 10.])

Cread dos arrays usando el método random.randint de Numpy con 80 elementos cada uno con números del 1-100, con los siguientes nombres array1 y array2.

In [12]:
array1=np.random.randint(1,100,(80))
array2=np.random.randint(1,100,(80))

Extraed los valores únicos de cada uno de los arrays y los guardáis en variables en las que se les llame array1 y array2.

In [13]:
array1=np.unique(array1)
array1

array([ 1,  3,  6,  7, 10, 11, 14, 15, 16, 17, 18, 21, 22, 23, 25, 26, 29,
       30, 34, 36, 37, 41, 43, 44, 46, 47, 48, 49, 50, 54, 55, 56, 57, 60,
       62, 64, 67, 68, 70, 71, 72, 76, 78, 79, 83, 84, 85, 87, 88, 90, 92,
       93, 94, 97, 98, 99])

In [14]:
array2=np.unique(array2)
array2

array([ 1,  6,  8,  9, 10, 15, 16, 17, 18, 20, 21, 23, 25, 26, 27, 29, 31,
       32, 33, 35, 36, 39, 40, 42, 43, 45, 48, 49, 51, 54, 55, 56, 61, 63,
       64, 65, 67, 68, 69, 71, 75, 78, 79, 80, 82, 83, 84, 85, 87, 88, 89,
       92, 93, 95, 99])

Identificad los elementos presentes en el array1 pero no en el array2 y asiganarlo a una variable que se llame array3.

In [15]:
array3=np.setdiff1d(array1,array2)
array3

array([ 3,  7, 11, 14, 22, 30, 34, 37, 41, 44, 46, 47, 50, 57, 60, 62, 70,
       72, 76, 90, 94, 97, 98])

Identificad los elementos presentes en el array2 pero no en el array1 y asiganarlo a una variable que se llame array4.

In [16]:
array4=np.setdiff1d(array2,array1)
array4

array([ 8,  9, 20, 27, 31, 32, 33, 35, 39, 40, 42, 45, 51, 61, 63, 65, 69,
       75, 80, 82, 89, 95])

Identificad los elementos presentes en ambos arrays y asiganarlos a una variable que se llame array5.

In [17]:
array5=np.intersect1d(array1,array2)
array5

array([ 1,  6, 10, 15, 16, 17, 18, 21, 23, 25, 26, 29, 36, 43, 48, 49, 54,
       55, 56, 64, 67, 68, 71, 78, 79, 83, 84, 85, 87, 88, 92, 93, 99])

¿Cuál es la relación que existe entre todos estos arrays?  
💡 Pista 💡 Tendréis que usar las longitudes de cada uno de los arrays creados.

In [18]:
print(f'{len(array1)},{len(array2)},{len(array3)},{len(array4)},{len(array5)}')

56,55,23,22,33


En este caso, 23 elementos unicos del array 1 estan contenidos en el 2. A su vez. 22 del 2 en el array 1. En total comparten 33 valores unicos diferentes.
Asi que si a 56, los valores unicos de 1, le restamos, los comunes totales(33), el resto coincide con los elementos unicos contenidos del array 1 en el 2(22), y viceversa.
