## NUMPY III Funciones

Cread un array de tres dimensiones de 2 matrices, 3 filas y 5 columnas cuyos valores solo tengan 1 decimales.

In [2]:
import numpy as np

In [3]:
array=np.round(np.random.random_sample((2,3,5)),decimals=1)
array

array([[[0. , 0.9, 0.2, 0.9, 1. ],
        [0. , 0.2, 0.7, 0.9, 0.3],
        [0.6, 0.6, 0.3, 0.1, 0.4]],

       [[0.3, 0.8, 0.2, 0.2, 0.4],
        [1. , 0.3, 0.1, 1. , 0.5],
        [0.4, 0.2, 0.4, 1. , 0.6]]])

Sobre el array creado anteriormente, extraed:

Calculad la media del array y almacenarlos en una variable. Redondead a un decimal.

In [4]:
array_media=np.round(np.mean(array), decimals=1)
array_media

0.5

Calculad el valor máximo del array y almacenarlos en una variable. Redondead a un decimal.

In [5]:
array_max=np.round(np.max(array), decimals=1)
array_max

1.0

Calculad el valor mínimo del array y almacenarlos en una variable. Redondead a un decimal.

In [6]:
array_min=np.round(np.min(array), decimals=1)
array_min

0.0

Cread un array vacío con la misma forma y dimensiones que el array creado anteriormente.


In [7]:
array_vacio=np.empty_like(array, dtype=str)
array_vacio

array([[['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']],

       [['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']]], dtype='<U1')

Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:  
Si el valor del array es igual que la media, se reemplaza por "A".  
Si el valor del array es mayor que la media, se reemplaza por "B".  
Si el valor del array es menor que la media, se reemplaza por "C".  
Si el valor es igual que el máximo, se reemplaza por "D".  
Si el valor es igual que el mínimo, se reemplaza por "E".

💡 Pista 💡 Tendréis que iterar por el array y cambiar los valores de la matriz vacía. Para eso tendremos que usar distintos condicionales.

In [8]:
for i in range(array.shape[0]):
    for numero in range(array.shape[1]):
        for numero2 in range(array.shape[2]):

            if array[i,numero,numero2]==array_media:
                array_vacio[i,numero,numero2]='A'
            elif array[i,numero,numero2]>array_media:
                array_vacio[i,numero,numero2]='B'
            elif array[i,numero,numero2]<array_media:
                array_vacio[i,numero,numero2]='C'
            elif array[i,numero,numero2]==array_max:
                array_vacio[i,numero,numero2]='D'
            else:
                if array[i,numero,numero2]==array_min:
                    array_vacio[i,numero,numero2]='E'
array_vacio

array([[['C', 'B', 'C', 'B', 'B'],
        ['C', 'C', 'B', 'B', 'C'],
        ['B', 'B', 'C', 'C', 'C']],

       [['C', 'B', 'C', 'C', 'C'],
        ['B', 'C', 'C', 'B', 'A'],
        ['C', 'C', 'C', 'B', 'B']]], dtype='<U1')

Estupendo, tenemos un array con strings.  
Ahora realizaremos un ejercicio similar al anterior, pero en este caso nos crearemos un array vacío unidimensional de 30 elementos.  
Al final de este ejercicio acabaremos teniendo un array de tres dimensiones con la misma forma que el primero que nos creamos.

In [9]:
array_vacio2=np.empty(30)
array_vacio2

array([0. , 0.9, 0.2, 0.9, 1. , 0. , 0.2, 0.7, 0.9, 0.3, 0.6, 0.6, 0.3,
       0.1, 0.4, 0.3, 0.8, 0.2, 0.2, 0.4, 1. , 0.3, 0.1, 1. , 0.5, 0.4,
       0.2, 0.4, 1. , 0.6])

En este caso:  
Si el valor del array creado en el ejercicio anterior es "A" o "B" lo reemplazaremos por 1  
Si el valor del array creado en el ejercicio anterior es "C" o "D" lo reemplazaremos por 2  
Si el valor del array creado en el ejercicio anterior es "E" lo reemplazaremos por 3.

In [38]:
array_plano1= []
array_plano2= []
array_plano3 =[]
for i in range(array_vacio.shape[0]):
    for numero in range(array_vacio.shape[1]):
        for numero2 in range(array_vacio.shape[2]):
            print(numero2)
            #array_vacio2(array_vacio[numero2])
            #print(array_plano)
            #for z in array_plano:
                #print(z)
                #for y in array_plano:
                    #print(y)
            if array_vacio[i,numero,numero2]=='A': 
                     array_vacio2[i,numero,numero2]=1
                     #print(array_vacio2)
            elif array_vacio[numero2]=='B':
                        array_vacio2[numero2]=1

            elif array_vacio[numero2]=='C':
                        array_vacio2[numero2]=2
            elif array_vacio[numero2]=='D':
                        array_vacio2[numero2]=2
            else:
                    array_vacio2[numero2]=3
                
array_vacio2


0


AttributeError: 'numpy.ndarray' object has no attribute 'loc'

In [31]:

for i in range(array_vacio.shape[0]):
    for numero in range(array_vacio.shape[1]):
        for numero2 in range(array_vacio.shape[2]):
            if array_vacio[i,numero,numero2]== 'A':
                array_vacio2[i]=1
            elif array_vacio[i,numero,numero2] == 'B':
                array_vacio2[i]=1
            elif array_vacio[i,numero,numero2] == 'C':
                array_vacio2[i] = 2
            elif array_vacio[i,numero,numero2]== 'D':
                array_vacio2[i]= 2
            else:
                 
                    array_vacio2[i]= 3
array_vacio2

array([2. , 1. , 0.2, 0.9, 1. , 0. , 0.2, 0.7, 0.9, 0.3, 0.6, 0.6, 0.3,
       0.1, 0.4, 0.3, 0.8, 0.2, 0.2, 0.4, 1. , 0.3, 0.1, 1. , 0.5, 0.4,
       0.2, 0.4, 1. , 0.6])

Una vez que hayas reemplazado todos los valores cambiad la forma del array para que sea de tres dimensiones, con 2 matrices, 3 filas y 5 columnas.