## NUMPY III Funciones

Cread un array de tres dimensiones de 2 matrices, 3 filas y 5 columnas cuyos valores solo tengan 1 decimales.

In [1]:
import numpy as np

In [2]:
array=np.round(np.random.random_sample((2,3,5)),decimals=1)
array

array([[[1. , 0.7, 0.8, 0.7, 0. ],
        [0.2, 0.2, 0.8, 0.1, 1. ],
        [0.2, 0.6, 0.5, 0.6, 0.5]],

       [[0.6, 0.4, 0.7, 1. , 1. ],
        [0.9, 0.9, 0.2, 0.9, 0.8],
        [0.4, 0.6, 0.8, 0.3, 0.7]]])

Sobre el array creado anteriormente, extraed:

Calculad la media del array y almacenarlos en una variable. Redondead a un decimal.

In [3]:
array_media=np.round(np.mean(array), decimals=1)
array_media

0.6

Calculad el valor máximo del array y almacenarlos en una variable. Redondead a un decimal.

In [4]:
array_max=np.round(np.max(array), decimals=1)
array_max

1.0

Calculad el valor mínimo del array y almacenarlos en una variable. Redondead a un decimal.

In [5]:
array_min=np.round(np.min(array), decimals=1)
array_min

0.0

Cread un array vacío con la misma forma y dimensiones que el array creado anteriormente.


In [6]:
array_vacio_letras=np.empty_like(array, dtype=str)
array_vacio_letras

array([[['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']],

       [['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']]], dtype='<U1')

Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:  
- Si el valor del array es igual que la media, se reemplaza por "A".  
- Si el valor del array es mayor que la media, se reemplaza por "B".  
- Si el valor del array es menor que la media, se reemplaza por "C".  
- Si el valor es igual que el máximo, se reemplaza por "D".  
- Si el valor es igual que el mínimo, se reemplaza por "E".

💡 Pista 💡 Tendréis que iterar por el array y cambiar los valores de la matriz vacía. Para eso tendremos que usar distintos condicionales.

In [8]:
for i in range(array.shape[0]):
    for numero in range(array.shape[1]):
        for numero2 in range(array.shape[2]):

            if array[i,numero,numero2]==array_media:
                array_vacio_letras[i,numero,numero2]='A'
            elif array[i,numero,numero2]>array_media:
                array_vacio_letras[i,numero,numero2]='B'
            elif array[i,numero,numero2]<array_media:
                array_vacio_letras[i,numero,numero2]='C'
            elif array[i,numero,numero2]==array_max:
                array_vacio_letras[i,numero,numero2]='D'
            else:
                if array[i,numero,numero2]==array_min:
                    array_vacio_letras[i,numero,numero2]='E'
array_vacio_letras

array([[['B', 'B', 'B', 'B', 'C'],
        ['C', 'C', 'B', 'C', 'B'],
        ['C', 'A', 'C', 'A', 'C']],

       [['A', 'C', 'B', 'B', 'B'],
        ['B', 'B', 'C', 'B', 'B'],
        ['C', 'A', 'B', 'C', 'B']]], dtype='<U1')

Estupendo, tenemos un array con strings.  
Ahora realizaremos un ejercicio similar al anterior, pero en este caso nos crearemos un array vacío unidimensional de 30 elementos.  
Al final de este ejercicio acabaremos teniendo un array de tres dimensiones con la misma forma que el primero que nos creamos.

In [11]:
array_vacio_numeros=np.empty(30)
array_vacio_numeros

array([1. , 0.7, 0.8, 0.7, 0. , 0.2, 0.2, 0.8, 0.1, 1. , 0.2, 0.6, 0.5,
       0.6, 0.5, 0.6, 0.4, 0.7, 1. , 1. , 0.9, 0.9, 0.2, 0.9, 0.8, 0.4,
       0.6, 0.8, 0.3, 0.7])

En este caso:  
- Si el valor del array creado en el ejercicio anterior es "A" o "B" lo reemplazaremos por 1  
- Si el valor del array creado en el ejercicio anterior es "C" o "D" lo reemplazaremos por 2  
- Si el valor del array creado en el ejercicio anterior es "E" lo reemplazaremos por 3.

In [12]:
array_vacio_letras.shape # verificamos las medidas del array de letras

(2, 3, 5)

In [13]:
array_vacio_numeros.shape # Verificamos las medidas del array vacio para numeros

(30,)

In [14]:
# Modificamos la forma de nuestro array donde vamos a cargar los numeros.
array_numeros = array_vacio_numeros.reshape(array_vacio_letras.shape)

In [15]:
for i in range(array_vacio_letras.shape[0]):
    for numero in range(array_vacio_letras.shape[1]):
        for numero2 in range(array_vacio_letras.shape[2]):

                    if array_vacio_letras[i,numero,numero2]==  'A': 
                        array_numeros[i,numero,numero2]=1

                    elif  array_vacio_letras[i,numero,numero2]==  'B' :
                        array_numeros[i,numero,numero2]=1
          
                    elif array_vacio_letras[i,numero,numero2]== 'C': 
                        array_numeros[i,numero,numero2]=2

                    elif  array_vacio_letras[i,numero,numero2]==  'D' :
                        array_numeros[i,numero,numero2]=2
       
                    else:
                        array_vacio_numeros[i,numero,numero2]=3


In [16]:
array_vacio_letras #recordamos el array de letras.

array([[['B', 'B', 'B', 'B', 'C'],
        ['C', 'C', 'B', 'C', 'B'],
        ['C', 'A', 'C', 'A', 'C']],

       [['A', 'C', 'B', 'B', 'B'],
        ['B', 'B', 'C', 'B', 'B'],
        ['C', 'A', 'B', 'C', 'B']]], dtype='<U1')

In [17]:
array_numeros # Verificamos que se modificaron los valores del array de numeros.

array([[[1., 1., 1., 1., 2.],
        [2., 2., 1., 2., 1.],
        [2., 1., 2., 1., 2.]],

       [[1., 2., 1., 1., 1.],
        [1., 1., 2., 1., 1.],
        [2., 1., 1., 2., 1.]]])